### ISSUE TITLE
fix bug in `transform_inputs_complete.R`

### ISSUE THREAD

**Issue by liz-fw** [Reorienting-to-Recovery/fallRunDSM#48]
when running `transform_inputs_complete.R`, I get an error:

https://github.com/Reorienting-to-Recovery/DSMflow/blob/main/data-raw/tranform_inputs_complete.R#L178

It says it can't find the object `calsim_data`. Can you figure out what's going on here?

P.S. this issue is only assigned to `fallRunDSM` because I couldn't figure out how to link it to `DSMflow` rn

**Comment by ergz** [comment]
yeah it should be `calsim3_data` not `calsim_data` I do this at the top of scrip: `calsim3_data <- map_df(list.files("data-raw/calsim3/", pattern = ".xlsx", full.names = TRUE), process_dss_output)`

**Comment by liz-fw** [comment]
addressed
